name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-analyse:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      # Set MAVEN_HOME environment variable
      - name: Set Maven Home Directory
        id: maven_home
        run: |
          MAVEN_HOME=$(mvn help:evaluate -Dexpression=maven.home -q -DforceStdout)
          echo "MAVEN_HOME=$MAVEN_HOME" >> $GITHUB_ENV
          echo "MAVEN_HOME: $MAVEN_HOME"

      # Build the project and trigger SonarCloud analysis
      - name: Build and Analyze with SonarCloud
        run: ./gradlew clean build sonarqube --stacktrace --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}